In [231]:
import re
import pandas as pd
import numpy as np

user_data = pd.read_csv('messy_user_signups.csv')

print('Original rows:', len(user_data))
print('Unique user IDs:', user_data['user_id'].nunique())
print('Duplicate user IDs:', user_data['user_id'].duplicated().sum())
print('Missing emails:', user_data['email'].isna().sum())

Original rows: 42
Unique user IDs: 32
Duplicate user IDs: 10
Missing emails: 7

In [232]:
def parse_date(s):
    if pd.isna(s):
        return pd.NaT

    s = str(s).strip().replace('/', '-').replace('.', '-')

    fmt = '%Y-%m-%d' if re.match(r'^\d{4}-', s) else '%d-%m-%Y'

    try:
        return pd.to_datetime(s, format=fmt)
    except ValueError:
        return pd.NaT

user_data['signup_date'] = user_data['signup_date'].apply(parse_date)

In [233]:
user_data.head(25)

,user_id,name,email,signup_date,country
0,1001,Sara Ahmadi,sara.ahmadi@example.com,2026-03-05,Iran
1,1002,Reza Karimi,NaN,2026-03-05,IRAN
2,1003,Mina Hosseini,mina.h@example.com,2026-03-07,iran
3,1004,Daniel Smith,dan.smith@example.com,2026-03-14,United States
4,1005,Emily Carter,emily.c@example.com,2026-03-15,united states
5,1006,Jin Park,jin.park@example.com,2026-03-16,South Korea
6,1007,Yuki Tanaka,NaN,2026-03-17,JAPAN
7,1008,Amir Rezaei,amir.r@example.com,2026-03-18,Iran
8,1009,Sofia Rossi,sofia.rossi@example.com,2026-03-19,Italy
9,1010,Lucas Martin,lucas.m@example.com,2026-03-20,FRANCE
10,1011,Noah Wilson,NaN,2026-03-21,United States
11,1012,Hana Kim,hana.kim@example.com,2026-03-22,south korea
12,1013,Kenji Sato,kenji.s@example.com,2026-03-23,Japan
13,1014,Emma Dubois,emma.d@example.com,2026-03-24,France
14,1015,Ali Mohammadi,ali.m@example.com,2026-03-25,IRAN
15,1016,Giulia Bianchi,NaN,2026-03-26,italy
16,1017,Oliver Brown,oliver.b@example.com,2026-03-27,united states
17,1018,Seo-yeon Lee,seoyeon.lee@example.com,2026-03-28,South Korea
18,1019,Akira Ito,akira.ito@example.com,2026-03-29,japan
19,1020,Camille Bernard,camille.b@example.com,2026-03-30,France
20,1021,Nima Salehi,nima.s@example.com,2026-04-01,iran
21,1022,Marco Conti,marco.c@example.com,2026-04-02,Italy
22,1023,Maya Johnson,NaN,2026-04-03,USA
23,1024,Min-jun Choi,minjun.c@example.com,2026-04-04,KOREA
24,1025,Haruto Yamada,haruto.y@example.com,2026-04-05,Japan

In [234]:
user_data.isna().sum()

user_id        0
name           0
email          7
signup_date    0
country        0
dtype: int64

In [235]:
np.shape(user_data)

(42, 5)

In [236]:
len(user_data['user_id'].unique())

32

In [237]:
repeated_rows = user_data[user_data.duplicated(subset=['user_id'], keep= False)]
repeated_rows.sort_values('user_id')

,user_id,name,email,signup_date,country
0,1001,Sara Ahmadi,sara.ahmadi@example.com,2026-03-05,Iran
30,1001,Sara Ahmadi,sara.ahmadi@example.com,2026-03-05,Iran
39,1002,Reza Karimi,NaN,2026-03-05,Iran
1,1002,Reza Karimi,NaN,2026-03-05,IRAN
31,1004,Daniel Smith,dan.smith@example.com,2026-03-14,UNITED STATES
3,1004,Daniel Smith,dan.smith@example.com,2026-03-14,United States
32,1007,Yuki Tanaka,yuki.tanaka@example.com,2026-03-17,Japan
6,1007,Yuki Tanaka,NaN,2026-03-17,JAPAN
8,1009,Sofia Rossi,sofia.rossi@example.com,2026-03-19,Italy
37,1009,Sofia Rossi,sofia.rossi@example.com,2026-03-19,Italy
38,1012,Hana Kim,hana.kim@example.com,2026-03-22,South Korea
11,1012,Hana Kim,hana.kim@example.com,2026-03-22,south korea
14,1015,Ali Mohammadi,ali.m@example.com,2026-03-25,IRAN
33,1015,Ali Mohammadi,ali.m@example.com,2026-03-25,Iran
34,1020,Camille Bernard,camille.b@example.com,2026-03-30,FRANCE
19,1020,Camille Bernard,camille.b@example.com,2026-03-30,France
22,1023,Maya Johnson,NaN,2026-04-03,USA
35,1023,Maya Johnson,maya.j@example.com,2026-04-03,United States
36,1028,Isabella Romano,isabella.r@example.com,2026-04-08,Italy
27,1028,Isabella Romano,isabella.r@example.com,2026-04-08,ITALY

In [238]:
user_data['user_id'].value_counts() [lambda x: x > 1]

user_id
1001    2
1002    2
1004    2
1007    2
1009    2
1012    2
1015    2
1020    2
1023    2
1028    2
Name: count, dtype: int64

In [239]:
user_data = user_data.drop(index= [30, 31, 6, 37, 11, 33, 34, 22, 27, 39])

In [240]:
np.shape(user_data)

(32, 5)

In [242]:
user_data['country'] = (
    user_data['country']
    .str.strip()
    .str.title()
    .replace({
        'Korea': 'South Korea',
        'Usa': 'United States'
    })
)
user_data['name'] = user_data['name'].str.strip()

In [245]:
print('Cleaned rows:', len(user_data))
print('Unique user IDs:', user_data['user_id'].nunique())
print('Duplicate user IDs:', user_data['user_id'].duplicated().sum())
print('Missing emails:', user_data['email'].isna().sum())
print('Missing dates:', user_data['signup_date'].isna().sum())

Cleaned rows: 32
Unique user IDs: 32
Duplicate user IDs: 0
Missing emails: 4
Missing dates: 0

In [244]:
user_data.to_csv('cleaned_user_signups.csv', index= False)